name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc[0-9]+'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Setup ko
        uses: ko-build/setup-ko@v0.6

      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ""
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=sha,format=long

      - name: Build and push images
        env:
          TAGS: ${{ steps.meta.outputs.tags }}
        run: ko build cmd/server/main.go --bare --tags $(echo $TAGS | tr ' ' ',')

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          generateReleaseNotes: true
          prerelease: ${{ contains(github.ref, '-rc.') }}
          skipIfReleaseExists: true